# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialbot', '0002_auto_20180915_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
