# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialbot', '0003_auto_20180915_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_no',
        ),
    ]
