# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialbot', '0004_remove_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
