# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialbot', '0006_auto_20181025_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
