# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialbot', '0007_auto_20181025_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='has_liked',
            field=models.BooleanField(default=False),
        ),
    ]
